"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { AdminCard } from "@/components/admin/layout";
import AdminTripMap from "@/components/admin/AdminTripMap";
import { Copy, ExternalLink, MapPin } from "lucide-react";

type Station = { _id: string; objectId: number; name: string; zones: string; stationType: string; lat: number; lng: number; active: boolean };
type Result = { stations: Station[]; page: number; totalPages: number; total: number; filters?: { zones: string[]; stationTypes: string[] } };
const input = { border: "1px solid var(--color-border)", borderRadius: 8, padding: "9px 10px", fontSize: 14, background: "var(--color-panel)" } as const;
const button = { border: 0, borderRadius: 8, padding: "8px 11px", fontWeight: 700, background: "var(--color-primary)", color: "var(--color-on-primary)", cursor: "pointer" } as const;

export default function StationManagement({ regionCode }: { regionCode: string }) {
  const [result, setResult] = useState<Result>({ stations: [], page: 1, totalPages: 1, total: 0 });
  const [query, setQuery] = useState(""); const [zone, setZone] = useState(""); const [stationType, setStationType] = useState("");
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState("40"); const [focusPoint, setFocusPoint] = useState<{ lat: number; lng: number } | null>(null); const [message, setMessage] = useState<string | null>(null);
  const mapRef = useRef<HTMLDivElement | null>(null);
  const request = useCallback(async (url: string, init?: RequestInit) => { const glue = url.includes("?") ? "&" : "?"; const res = await fetch(`${url}${glue}region=${encodeURIComponent(regionCode)}`, init); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data.error ?? "Station request failed."); return data; }, [regionCode]);
  const load = useCallback(async () => { try { const data = await request(`/api/admin/stations?q=${encodeURIComponent(query)}&zone=${encodeURIComponent(zone)}&stationType=${encodeURIComponent(stationType)}&page=${page}&limit=${pageSize}`); setResult(data); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not load stations."); } }, [page, pageSize, query, request, stationType, zone]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function copyCoordinates(station: Station) { const coordinates = `${station.lat}, ${station.lng}`; try { await navigator.clipboard.writeText(coordinates); setMessage(`Coordinates copied: ${coordinates}`); } catch { setMessage("Could not copy coordinates. Please copy them manually."); } }
  function takeThere(station: Station) { setFocusPoint({ lat: station.lat, lng: station.lng }); mapRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); setMessage(`Map focused on ${station.name}.`); }
  function applyFilters() { setPage(1); }
  return <div style={{ display: "grid", gap: 20 }}>
    <AdminCard title="Station map" description="Station nodes only. Use the mouse wheel to zoom and select “Take me there” for a precise location."><div ref={mapRef}><AdminTripMap stationOnly focusPoint={focusPoint} points={result.stations.map((station) => ({ lat: station.lat, lng: station.lng, label: `#${station.objectId} ${station.name}`, kind: "station" as const }))} /></div></AdminCard>
    <AdminCard title="Station list" description="Search by object ID, name, landmark, or zone.">
      <div style={{ display: "grid", gridTemplateColumns: "minmax(180px, 2fr) repeat(3, minmax(120px, 1fr)) auto", gap: 10, marginBottom: 16 }}><input style={input} value={query} placeholder="Search stations" onChange={(event) => setQuery(event.target.value)} /><select style={input} value={zone} onChange={(event) => setZone(event.target.value)}><option value="">All zones</option>{(result.filters?.zones ?? []).map((value) => <option key={value} value={value}>{value}</option>)}</select><select style={input} value={stationType} onChange={(event) => setStationType(event.target.value)}><option value="">All types</option>{(result.filters?.stationTypes ?? []).map((value) => <option key={value} value={value}>{value}</option>)}</select><select aria-label="Stations per page" style={input} value={pageSize} onChange={(event) => { setPageSize(event.target.value); setPage(1); }}><option value="10">10 / page</option><option value="30">30 / page</option><option value="50">50 / page</option><option value="70">70 / page</option><option value="90">90 / page</option><option value="all">All</option></select><button type="button" style={button} onClick={applyFilters}>Apply filters</button></div>
      {message && <p role="status" style={{ margin: "0 0 12px" }}>{message}</p>}
      <div style={{ overflowX: "auto" }}><table className="admin-table" style={{ width: "100%", minWidth: 850, borderCollapse: "separate", borderSpacing: 0 }}><thead><tr>{["ID", "Name", "Type", "Zone", "Coordinates", "Status", "Actions"].map((head) => <th key={head} style={{ padding: "12px 14px", textAlign: "left" }}>{head}</th>)}</tr></thead><tbody>{result.stations.map((station) => <tr key={station._id}><td style={{ padding: "12px 14px" }}>{station.objectId}</td><td style={{ padding: "12px 14px" }}>{station.name}</td><td style={{ padding: "12px 14px" }}>{station.stationType}</td><td style={{ padding: "12px 14px" }}>{station.zones}</td><td style={{ padding: "12px 14px", whiteSpace: "nowrap" }}>{station.lat.toFixed(5)}, {station.lng.toFixed(5)}</td><td style={{ padding: "12px 14px" }}>{station.active ? "Active" : "Inactive"}</td><td style={{ padding: "12px 14px" }}><div style={{ display: "flex", gap: 6 }}><a aria-label={`View ${station.name} in Google Maps`} title="View in Google Maps" style={{ ...button, display: "inline-flex", padding: 8 }} href={`https://www.google.com/maps?q=${station.lat},${station.lng}`} target="_blank" rel="noreferrer"><ExternalLink size={16} aria-hidden="true" /></a><button aria-label={`Copy coordinates for ${station.name}`} title="Copy coordinates" type="button" style={{ ...button, background: "var(--color-secondary)", display: "inline-flex", padding: 8 }} onClick={() => void copyCoordinates(station)}><Copy size={16} aria-hidden="true" /></button><button aria-label={`Show ${station.name} on map`} title="Take me there" type="button" style={{ ...button, display: "inline-flex", padding: 8 }} onClick={() => takeThere(station)}><MapPin size={16} aria-hidden="true" /></button></div></td></tr>)}</tbody></table></div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginTop: 16 }}><span>{result.total} stations{pageSize === "all" ? "" : ` · Page ${result.page} of ${result.totalPages}`}</span>{pageSize !== "all" && <div style={{ display: "flex", gap: 8 }}><button type="button" style={button} disabled={page <= 1} onClick={() => setPage((current) => current - 1)}>Previous</button><button type="button" style={button} disabled={page >= result.totalPages} onClick={() => setPage((current) => current + 1)}>Next</button></div>}</div>
    </AdminCard>
  </div>;
}
