"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { TripData } from "./TripCycle";
import type { TripPoint } from "@/lib/store/useTripStore";
import { isSharedVehicle } from "@/lib/geo/stations";
import { formatDisplayName, reverseGeocode } from "@/lib/nominatim";
import GoogleMapCanvas from "@/components/map/GoogleMapCanvas";
import { MAP_STYLE } from "@/lib/googleMapsStyle";
import type { MapSettings } from "@/lib/config/mapSettings";
import type { RegionCode, RegionConfig } from "@/lib/config/regions";

type ZoneFeature = { geometry?: { type: "Polygon" | "MultiPolygon"; coordinates?: number[][][] | number[][][][] } };
type Props = { regionCode: RegionCode; mapConfig: RegionConfig["map"]; mapSettings: MapSettings; trips: TripData[]; picking?: { tripId: string; field: "pickup" | "dropoff" | "stop"; stopId?: string } | null; onMapPick?: (point: TripPoint) => void; onStationSelect?: (tripId: string, field: "pickup" | "dropoff", stationId: number) => void; onCancelPick?: () => void };

function inRing(point: [number, number], ring: number[][]) { let inside = false; for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) { const [x1, y1] = ring[i]; const [x2, y2] = ring[j]; if (y1 > point[1] !== y2 > point[1] && point[0] < ((x2 - x1) * (point[1] - y1)) / (y2 - y1) + x1) inside = !inside; } return inside; }
function inZones(point: [number, number], features: ZoneFeature[]) { return features.some(({ geometry }) => { if (!geometry?.coordinates) return false; const polygons = geometry.type === "Polygon" ? [geometry.coordinates as number[][][]] : geometry.coordinates as number[][][][]; return polygons.some((polygon) => inRing(point, polygon[0] ?? []) && !polygon.slice(1).some((hole) => inRing(point, hole))); }); }

export default function CreateMapGoogle({ regionCode, mapConfig, mapSettings, trips, picking, onMapPick, onStationSelect, onCancelPick }: Props) {
  const mapRef = useRef<any>(null); const [mapReady, setMapReady] = useState(false); const [zones, setZones] = useState<ZoneFeature[]>([]);
  const points = useMemo(() => trips.flatMap((trip) => [trip.pickup, trip.dropoff, ...trip.stops.map((stop) => stop.point)].filter(Boolean) as TripPoint[]), [trips]);
  useEffect(() => { if (!mapSettings.showZones || regionCode !== "EG-CAIRO") { setZones([]); return; } let cancelled = false; fetch("/geo/zone_polygon.geojson").then((r) => r.json()).then((json) => { if (!cancelled) setZones((json.features ?? []).filter((feature: ZoneFeature) => feature.geometry?.type === "Polygon" || feature.geometry?.type === "MultiPolygon")); }).catch(() => setZones([])); return () => { cancelled = true; }; }, [mapSettings.showZones, regionCode]);
  useEffect(() => { const map = mapRef.current; const g = (window as any).google; if (!map || !g) return; const layers: any[] = []; const addMarker = (position: { lat: number; lng: number }, label: string, title: string, action?: () => void) => { const marker = new g.maps.Marker({ map, position, label, title }); if (action) marker.addListener("click", action); layers.push(marker); };
    zones.forEach(({ geometry }) => { if (!geometry?.coordinates) return; const polygons = geometry.type === "Polygon" ? [geometry.coordinates as number[][][]] : geometry.coordinates as number[][][][]; polygons.forEach((polygon) => layers.push(new g.maps.Polygon({ map, paths: polygon.map((ring) => ring.map(([lng, lat]) => ({ lat, lng }))), strokeColor: "#00C2A8", strokeWeight: 2, fillOpacity: 0 }))); });
    trips.forEach((trip, index) => { const color = ["#4361EE", "#F5A623", "#00C2A8"][index % 3]; if (trip.routeCoordinates?.length) layers.push(new g.maps.Polyline({ map, path: trip.routeCoordinates.map(([lat, lng]) => ({ lat, lng })), strokeColor: color, strokeWeight: 5 })); if (trip.pickup) addMarker(trip.pickup, "A", `Trip ${index + 1} pickup`); if (trip.dropoff) addMarker(trip.dropoff, "B", `Trip ${index + 1} dropoff`); if (!isSharedVehicle(trip.vehicleType)) trip.stops.forEach((stop, stopIndex) => stop.point && addMarker(stop.point, String(stopIndex + 1), `Trip ${index + 1} stop`)); if (isSharedVehicle(trip.vehicleType) && mapSettings.showStations) { trip.pickupStationOptions.forEach((station) => addMarker(station, "S", `Pickup station: ${station.name}`, () => onStationSelect?.(trip.id, "pickup", station.id))); trip.dropoffStationOptions.forEach((station) => addMarker(station, "S", `Dropoff station: ${station.name}`, () => onStationSelect?.(trip.id, "dropoff", station.id))); } }); if (points.length) { const bounds = new g.maps.LatLngBounds(); points.forEach((point) => bounds.extend(point)); map.fitBounds(bounds, 48); } return () => layers.forEach((layer) => layer.setMap?.(null)); }, [mapReady, mapSettings.showStations, onStationSelect, points, trips, zones]);
  const onClick = useCallback(async ({ lat, lng }: { lat: number; lng: number }) => { if (!picking || !onMapPick) return; if (mapSettings.showZones && (!zones.length || !inZones([lng, lat], zones))) { window.alert(zones.length ? "This location is outside the available service zones." : "The service zones are still loading. Please try again in a moment."); return; } let address = `${lat.toFixed(5)}, ${lng.toFixed(5)}`; try { const value = formatDisplayName(await reverseGeocode(lat, lng, "google")); if (value) address = value; } catch {} onMapPick({ address, lat, lng }); }, [mapSettings.showZones, onMapPick, picking, zones]);
  if (!process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY) return <div className="map-provider-unavailable">Google Maps is unavailable. Ask an administrator to configure the public Google Maps key or choose OpenStreetMap.</div>;
  return <div style={{ width: "100%", height: "100%", position: "relative" }}><GoogleMapCanvas center={mapConfig.defaultCenter} zoom={mapConfig.defaultZoom} onReady={(map) => { mapRef.current = map; setMapReady(Boolean(map)); }} onClick={onClick} options={{ disableDefaultUI: true, zoomControl: true, styles: mapSettings.canvasStyle === "light" ? MAP_STYLE : undefined, mapTypeId: mapSettings.canvasStyle === "satellite" ? "satellite" : "roadmap", draggableCursor: picking ? "crosshair" : undefined }} />{picking ? <div className="map-pick-banner">Click map to set {picking.field === "stop" ? "stop point" : picking.field}<button type="button" onClick={onCancelPick}>Cancel</button></div> : null}</div>;
}
